version: '3.8'

services:
  nginx:
    image: nginx:1.21.1
    restart: unless-stopped # これを入れておくと異常終了時などに自動再起動される
    ports:
      - "80:80"
    environment:
      TZ: Asia/Tokyo # コンテナ内の時刻を日本時間に設定。
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro # Nginx設定ファイルを読み取り専用にして壊れないようにする。
      - ./src:/var/www/
    depends_on:
      - php

  php:
    build: ./docker/php
    restart: unless-stopped
    environment:
      TZ: Asia/Tokyo # PHP内部時刻も日本時間に統一
    volumes:
      - ./src:/var/www/

  mysql:
    image: mysql:8.0.26
    environment:
      TZ: Asia/Tokyo # DBのタイムゾーンも日本時刻に
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro # MySQL設定ファイルを読み取り専用に
    healthcheck:
      # MySQLが実際に接続可能になるまでの監視を行う
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-plaravel_pass" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      TZ: Asia/Tokyo
      PMA_HOST: mysql
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_pass
    depends_on:
      mysql:
        condition: service_healthy # MySQLのhealthcheckが成功してから起動
    ports:
      - 8080:80
